# Generated by Django 2.2.2 on 2019-06-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cas_ng', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxygrantingticket',
            name='session_key',
            field=models.CharField(db_index=True, default='?', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sessionticket',
            name='session_key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
